import type { Dictionary } from "@/i18n/dictionaries";

export function wizardLabels(t: Dictionary): Record<string, string> {
  return {
    basics: t.event.stepBasics,
    location: t.event.stepLocation,
    registration: t.event.stepRegistration,
    review: t.event.stepReview,
    title: t.event.title,
    template: t.event.template,
    noTemplate: t.event.noTemplate,
    description: t.event.description,
    startsAt: t.event.startsAt,
    endsAt: t.event.endsAt,
    timezone: t.event.timezone,
    locationKind: t.event.locationKind,
    venueName: t.event.venueName,
    venueAddress: t.event.venueAddress,
    geocode: t.event.geocode,
    virtualUrl: t.event.virtualUrl,
    virtualProvider: t.event.virtualProvider,
    customPin: t.event.customPin,
    cover: t.event.cover,
    registrationMode: t.event.registrationMode,
    registrationPassword: t.event.registrationPassword,
    allowedDomains: t.event.allowedDomains,
    accessToken: t.event.accessToken,
    capacity: t.event.capacity,
    waitlist: t.event.waitlist,
    waitlistPresale: t.event.waitlistPresale,
    paid: t.event.paid,
    city: t.event.city,
    country: t.event.country,
    category: t.event.category,
    language: t.event.language,
    tags: t.event.tags,
    back: t.event.back,
    next: t.event.next,
    saveDraft: t.event.saveDraft,
    publish: t.event.publish,
    resume: t.event.resume,
  };
}
